name: CI-CD Pipeline

# Trigger the workflow on push events to the main branch
on:
  push:
    branches: ["main"]

jobs:
  mlops:
    name: Train + Build + Push Image + Deploy
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/kartiksri2005/Testing-dvc-integration-dashhub.mlflow
      MLFLOW_TRACKING_USERNAME: kartiksri2005
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      PYTHONPATH: .

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3  # cloning the gihub repo in ci workspace
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true  # allowing the commit back to repo (allowing write permissions)

      # Python setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[http]"

      # Configuring DVC remote credentials (uses DAGSHUB_TOKEN secret)
      - name: Configure DVC remote
        run: |
          dvc remote modify dagshub --local auth basic
          dvc remote modify dagshub --local user kartiksri2005
          dvc remote modify dagshub --local password ${{ secrets.DAGSHUB_TOKEN }}

      # Pulling cached data + artifacts from DagsHub
      - name: Pull DVC data
        run: dvc pull 

      # Runing ML pipeline 
      - name: Run ML pipeline
        run: dvc repro

      # Pushing new artifacts to DagsHub
      - name: Push artifacts to DagsHub
        run: dvc push

      # Moving artifacts to docker backend
      - name: Update backend artifacts
        run: python mlops_src/update_artifacts.py

      # Committing dvc.lock and logs to repo
      - name: Commit dvc.lock and pipeline logs
        run: |
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add dvc.lock logs/ || true
          git commit -m "CI pushing changes in dvc.lock and pipeline logs" || echo "No changes"
          git push || echo "Nothing to push"

      # Building and pushing docker image 
      - name: Build & Push Docker Image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker build -t aeroprice-backend ./docker_backend
          docker tag aeroprice-backend docker.io/${{ secrets.DOCKERHUB_USERNAME }}/aeroprice-backend:latest
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/aeroprice-backend:latest

      # Deploying to render
      - name: Deploy to Render
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_TOKEN" \
          -H "accept: application/json" \
          -H "content-type: application/json" \
          -d '{"image": "'"${{ secrets.DOCKERHUB_USERNAME }}"'/aeroprice-backend:latest"}' \
          https://api.render.com/deploy/srv-d9eam2bbc2fs73fk1ppg?key=7gotTI61apg


